@echo off
echo 🚀 Iniciando Snippets Desktop App...
echo.

echo [1/2] Iniciando React...
start "React Dev Server" cmd /k "npm run dev:react"

echo [2/2] Aguardando e iniciando Electron...
echo Aguarde o React carregar completamente antes de pressionar qualquer tecla...
pause

echo Iniciando Electron Desktop App...
npm run dev:electron