export const POPULAR_LANGUAGES = [
  'javascript',
  'typescript',
  'python',
  'java',
  'c#',
  'cpp',
  'c',
  'go',
  'rust',
  'php',
  'ruby',
  'swift',
  'kotlin',
  'scala',
  'sql',
  'bash',
  'shell',
  'powershell',
  'html',
  'css',
  'scss',
  'less',
  'json',
  'xml',
  'yaml',
  'yml',
  'markdown',
  'dockerfile',
  'docker',
  'react',
  'vue',
  'angular',
  'node.js',
  'nginx',
  'apache',
  'mysql',
  'postgresql',
  'mongodb',
  'redis',
  'git',
  'vim',
  'lua',
  'perl',
  'r',
  'matlab'
]

export function filterLanguages(query: string): string[] {
  const lowercaseQuery = query.toLowerCase()
  return POPULAR_LANGUAGES
    .filter(lang => lang.toLowerCase().includes(lowercaseQuery))
    .slice(0, 10) // Limit to 10 suggestions
}

export function getLanguageDisplayName(language: string): string {
  const displayNames: Record<string, string> = {
    'javascript': 'JavaScript',
    'typescript': 'TypeScript',
    'python': 'Python',
    'java': 'Java',
    'c#': 'C#',
    'cpp': 'C++',
    'c': 'C',
    'go': 'Go',
    'rust': 'Rust',
    'php': 'PHP',
    'ruby': 'Ruby',
    'swift': 'Swift',
    'kotlin': 'Kotlin',
    'scala': 'Scala',
    'sql': 'SQL',
    'bash': 'Bash',
    'shell': 'Shell',
    'powershell': 'PowerShell',
    'html': 'HTML',
    'css': 'CSS',
    'scss': 'SCSS',
    'less': 'Less',
    'json': 'JSON',
    'xml': 'XML',
    'yaml': 'YAML',
    'yml': 'YAML',
    'markdown': 'Markdown',
    'dockerfile': 'Dockerfile',
    'docker': 'Docker',
    'react': 'React',
    'vue': 'Vue.js',
    'angular': 'Angular',
    'node.js': 'Node.js',
    'nginx': 'Nginx',
    'apache': 'Apache',
    'mysql': 'MySQL',
    'postgresql': 'PostgreSQL',
    'mongodb': 'MongoDB',
    'redis': 'Redis',
    'git': 'Git',
    'vim': 'Vim',
    'lua': 'Lua',
    'perl': 'Perl',
    'r': 'R',
    'matlab': 'MATLAB'
  }
  
  return displayNames[language.toLowerCase()] || language
}